#!/bin/sh

prefix=/usr
exec_prefix=${prefix}
exec_prefix_set=no
libdir=${prefix}/lib/x86_64-linux-gnu

usage="\
Usage: freetype-config [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs] [--static-libs]"

if test $# -eq 0; then
      echo "${usage}" 1>&2
      exit 1
fi

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | LC_ALL="C" sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo $prefix
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo $exec_prefix
      ;;
    --version)
      echo 9.0.0
# Its 2.10.4 but yeah, otherwise wont use freetype
      ;;
    --cflags)
      echo -I${prefix}/include/freetype2 -I${prefix}/include/freetype2/freetype
      ;;
    --libs)
      echo -L${prefix}/lib/x86_64-linux-gnu -lfreetype
      ;;
#    --static-libs)
#    --libs|--static-libs)
#      echo -L${prefix}/lib/x86_64-linux-gnu  -lSDL  -lpthread  -lm -ldl  -lasound -lm -ldl -lpthread -lpulse-simple -lpulse  -lX11 -lXext -L/usr/lib/x86_64-linux-gnu -lcaca -lpthread
#      ;;
    *)
      echo "${usage}" 1>&2
      exit 1
      ;;
  esac
  shift
done
